modLoader = "javafml"
loaderVersion = "[FORGE_LOADER,)"
license = "MIT"
issueTrackerURL = "${GIT_REPO}/issues"
[[mods]]
modId = "${MOD_ID}"
version = "${version}"
displayName = "${NAME}"
displayURL = "${CURSE_HOMEPAGE_LINK}"
updateJSONURL = "https://updates.blamejared.com/get?n=${MOD_ID}&gv=${MINECRAFT}&ml=forge"
logoFile = "logo.png"
authors = "${AUTHOR}"
description = "${DESCRIPTION}"
itemIcon = "${ITEM_ICON}"
[[dependencies.${MOD_ID}]]
modId = "forge"
mandatory = true
versionRange = "[FORGE_LOADER,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${MOD_ID}]]
modId = "minecraft"
mandatory = true
versionRange = "[${MINECRAFT}]"
ordering = "NONE"
side = "BOTH"
