modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT"
issueTrackerURL = "https://github.com/CraftTweaker/CraftTweaker/issues"
[[mods]]
modId = "crafttweaker"
version = "${file.jarVersion}"
displayName = "CraftTweaker"
displayURL = "https://minecraft.curseforge.com/projects/crafttweaker"
updateJSONURL = "https://updates.blamejared.com/get?n=crafttweaker&gv=1.20.1"
logoFile = "logo.png"
authors = "Jaredlll08, Kindlich, StanHebben and TheSilkMiner"
description = "Customize your minecraft experience!"
itemIcon = "minecraft:crafting_table"
[[dependencies.crafttweaker]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.crafttweaker]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
