name: Bug Report
description: Report a bug or problem with CraftTweaker
body:
    -   type: markdown
        attributes:
            value: |
                If this bug occurs in a modpack, please report this to the modpack author.
                
                If you are using an unnofficial version of CraftTweaker please report it to the person who gave you the version.
                
                Please also look at the other issues to make sure that you are not creating a duplicate.
    -   type: textarea
        attributes:
            label: Issue description
            description: |
                A clear description of the issue. 
                
                **Please** do not just say "it doesn't work".
                
                The more information we have, the easier it is to help.
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Steps to reproduce
            description: |
                This is only if there are any specific steps to reproduce the bug.
                
                You do not need to list things such as "write the following code in a script".
            placeholder: |
                If there are specific steps that need to be taken to reproduce this issue list them here.
    -   type: input
        attributes:
            label: "Script used"
            description: "Please provide a [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. (Make sure that it isn't set to expire!)"
        validations:
            required: true
    -   type: input
        attributes:
            label: "The crafttweaker.log file"
            description: |
                Please provide a [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. (Make sure that it isn't set to expire!)
                
                You can use `/ct log` in-game to open the crafttweaker.log file.
        validations:
            required: true
    -   type: dropdown
        id: minecraft-version
        attributes:
            label: Minecraft version
            description: |
                What version of Minecraft are you using?
                
                If you version isn't listed, then select "other" and list your version in the issue description.
            options:
                - 1.20
                - 1.19.4
                - 1.19.3
                - 1.19
                - 1.18
                - 1.16
                - 1.12
                - Other
        validations:
            required: true
    -   type: dropdown
        id: modloader
        attributes:
            label: Modloader
            description: |
                What Modloader are you using?
                
                If you have tested on both modloaders and the issue affects both, then select all
            options:
                - All
                - Fabric
                - Forge
        validations:
            required: true
    -   type: input
        attributes:
            label: Modloader version
            description: What version of Forge / Fabric loader are you using?
            placeholder: 39.1.0 / 0.12.12
        validations:
            required: true
    -   type: input
        attributes:
            label: CraftTweaker version
            description: What version of CraftTweaker are you using?
            placeholder: 9.0.0+10
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Other relevant information
            description: Any other relevant information that is related to this issue, such as other mods and their versions
    -   type: input
        attributes:
            label: "The latest.log file"
            description: "Please provide a [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. (Make sure that it isn't set to expire!)"
        validations:
            required: true
