package minetweaker.mc1120;

import java.util.List;

/**
 * @author Stan
 */
public class MineTweakerRegistry {
    
    public static void getClasses(List<Class> classes) {
        // method stub, actual content is generated by build process
    }
}
