/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package minetweaker.mc1710;

import java.util.List;

/**
 *
 * @author Stan
 */
public class MineTweakerRegistry {
	public static void getClasses(List<Class> classes) {
		// method stub, actual content is generated by build process
	}
}
