modLoader = "javafml"
loaderVersion = "[${NEO_FORGE_LOADER},)"
license = "MIT"
issueTrackerURL = "${GIT_REPO}/issues"
[[mods]]
modId = "${MOD_ID}"
version = "${version}"
displayName = "${NAME}"
displayURL = "${CURSE_HOMEPAGE_LINK}"
updateJSONURL = "https://updates.blamejared.com/get?n=${MOD_ID}&gv=${MINECRAFT}&ml=neoforge"
logoFile = "logo.png"
authors = "${AUTHOR}"
description = "${DESCRIPTION}"
itemIcon = "${ITEM_ICON}"
[[mixins]]
config = "${MOD_ID}.mixins.json"
[[mixins]]
config = "${MOD_ID}.neoforge.mixins.json"
[[dependencies.${MOD_ID}]]
modId = "neoforge"
type = "required"
versionRange = "[${NEO_FORGE_LOADER},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${MOD_ID}]]
modId = "minecraft"
type = "required"
versionRange = "[${MINECRAFT}]"
ordering = "NONE"
side = "BOTH"
