/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package minetweaker;

import java.util.List;

/**
 *
 * @author Stan
 */
public class ClassRegistry {
	public static void getClasses(List<Class> output) {
		// method stub; contents generated by RegisterZenClassesTask
	}
}
