package minetweaker;

import java.util.List;

/**
 * The class registry provides the list of annotated classes to the scripting
 * system.
 * 
 * @author Stan Hebben
 */
public class ClassRegistry {
	public static void getClasses(List<Class> output) {
		// method stub; contents generated by RegisterZenClassesTask
	}
}
